project:
  type: website

website:
  site-url: dmswan.com
  repo-url: https://github.com/DMSwan/dmswan-site
  title: "Danny Swan"
  navbar:
    left:
      - posts.qmd
      - text: Publications
        href: publications.qmd
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      light: zephyr
      dark: darkly
    css: styles.css    
execute:
  freeze: auto


