---
title: "New site"
subtitle: "Hello Quarto & Positron"
date: "2025-08-19"
---

After I lost my job due to federal contract cancellations earlier this year, I started to consider what I wanted to do next. One option is data science stuff. The market is a little bit tough at the moment, and I may need to brush up on some skills. I also haven't touched by website since 2022, which feels like a bit of a bummer since I can't really use it in my application process lest I look silly.

Like many other people in the R Extended Universe circa 2021, I originally created my website using blogdown and Hugo. In a lot of ways, it was great! It worked with minimal fiddling, integrated R code and markdown, etc. However, the way that Hugo worked meant that if you didn't keep up with your site, it was pretty easy to get stuck with a site that was hard to update. This is one of the reasons that I haven't really touched my site since 2022. Updating it became kind of a pain. Enter Quarto, which is a sort of replacement/extension of the R Markdown document supported by Posit. There's still some fiddling, but overall it wasn't too painful to port the important stuff from my old website to this format. For reference, I used the following blog posts to help bootstrap my process:

-   <https://www.andreashandel.com/posts/2022-10-01-hugo-to-quarto-migration/>

-   <https://blog.djnavarro.net/posts/2022-04-20_porting-to-quarto/#fnref1>

I also poked around the github for my Ph.D. advisor's site (<https://github.com/jepusto/jepusto-quarto>) to see how he'd organized things.

In addition to shifting to Quarto, I'm using Positron instead of the familiar RStudio. If you're stuck in the past (like I was, just a few weeks ago) Positron is a new data science IDE that supports both R and Python natively. It's based on VSCode, but looks like RStudio. This is comforting if you've been using RStudio for about ten years. I've tried to stick my feet into the VSCode pool, but it can be disorienting if I'm also doing something else that I'm not as familiar with, like code in Python. One of the things I need to brush up on is the Python toolchain, like NumPy, Pandas, Scikit-Learn. *Maybe* Seaborn. I feel like I could probably still use ggplot2 for visualization, even I need to use Python for the rest of the toolchain. But I digress. Upskilling Python will be a *lot* easier with an IDE that feels comfortable.

At the time of this post, things are still under construction. For instance, I don't yet have a section for my publications or my resume. However, I wanted to get a new version this up and ready to go ASAP. More to come soon.